name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Frontend
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Type checking
        working-directory: ./frontend
        run: npm run type-check

      - name: Compile
        working-directory: ./frontend
        run: npm run build

      # Backend
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install package
        run: pip install './backend[dev,server]'

      - name: Type checking
        uses: jakebailey/pyright-action@v2.2.1
        with:
          version: 1.1.352
          working-directory: backend

      - name: Run test suite
        working-directory: ./backend
        run: pytest

      - name: Build sdist
        run: python -m build ./backend

      - name: Publish sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: 'backend/dist/*''
