name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt
      
      - name: Compile Cython
        run: |
          ls $pythonLocation/lib/python3.12/site-packages
          ls $pythonLocation/lib/python3.12/site-packages/numpy/core/include
          pip install setuptools
          export CFLAGS=$pythonLocation/lib/python3.12/site-packages/numpy/core/include/
          cythonize --inplace backend/core/model.pyx

      # Run test suite
      - name: Install dependencies
        run: |
          pip install pytest
          export PYTHONPATH=$PWD
          cd backend
          pytest test 
